#!/usr/bin/env python
# Chooses a random backgound from this folder.
import random
import os
from os.path import splitext, dirname, abspath, join
import subprocess

BG_IMAGES_DIR = dirname(abspath(__file__))
IMG_EXTENSIONS = (".png", ".jpg", ".jpeg")

def is_image_file(filename):
    _, file_ext = splitext(filename)
    return file_ext in IMG_EXTENSIONS

if __name__ == "__main__":
    images = list(filter(is_image_file, os.listdir(BG_IMAGES_DIR)))
    bg_image = random.choice(images)
    print("New background: {}".format(bg_image))
    command = "feh --bg-scale '{}'".format(join(BG_IMAGES_DIR, bg_image))
    subprocess.call(command, shell=True)
